### ISSUE TITLE
Tracking issue: Revamp build process

### ISSUE THREAD

**Issue by yue4u** [pixiv/three-vrm#1294]
Starting by https://github.com/pixiv/three-vrm/pull/1293 we are planned to revamp the build process.

Current TODOs:

- [ ] bundle dts as suggested in https://github.com/pixiv/three-vrm/issues/1289 https://github.com/pixiv/three-vrm/pull/1293
- [x] publish packages on CI https://github.com/pixiv/three-vrm/pull/1297
  - [x] adopt [npm package provenance](https://docs.npmjs.com/generating-provenance-statements)
- [x] check if we are still want to use rollup as the bundler, maybe swtich to tsup or esbuild #1411 
- [x] improve esm/cjs support #1411 
- [ ] maybe: mitigate to pnpm
